### ISSUE TITLE
Possibility to add custom fields

### ISSUE THREAD

**Issue by houshuang** [mneudert/plug_accesslog#4]
Is there a way to add custom fields? All of my users are logged in and authenticated, and their userid exists in the conn tuple, after the ensure_registered plug. I want this value added to each log line - how would I do this?

**Comment by mneudert** [comment]
It might be hacky but doable.

You could pass a logging function to the plug as shown in `test/plug/accesslog/logfunctions_test.exs`. This function will be called instead of writing to a configured logfile.

After manipulating the log to your liking you could then fetch the logfile device from `Plug.AccessLog.Logfile.get/1` and pass it with your custom log message to `Plug.AccessLog.Writer.write/2` (see `Plug.AccessLog` from line 44 onwards). Or just output it directly from your logging function.

For now this is probably the only way without having to modify the source.

But I think it would be a great addition to be able to register custom formatters or even be able to replace the existing ones. Definitely something I should include in the next release (including updated documentation for the `log` and `dontlog` functions...)...

**Comment by houshuang** [comment]
Thanks for your feedback. For now I did something fairly ugly :) https://github.com/mneudert/plug_accesslog/compare/master...houshuang:master

Works great though. I needed something quick, since we were deploying last night. Already 8500 hits logged :) 

I am thinking of expanding this by logging more contextual information - storing all the URL parameters wouldn't be nice because I have all kinds of session info in the URL (plug_paramsession), but perhaps each of my controllers could set a relevant value in conn.private (usually the id of whatever resource is stored etc). The other is that I'd love to store the time it took to process the request. Both of these require that the log entry is written at the end of the processing, and not at the beginning.

**Comment by mneudert** [comment]
My current plan is to introduce a new configuration parameter like `formatters: []` having the current Formatter as its default. Using a custom list would then run them in order and manipulate the logstring as needed. That would allow you to essentially do whatever you want with the message generation without worrying about the "default parameters".

Regarding the processing time you should look at `Plug.AccessLog.call/2`. The log writing is done using the `Plug.Conn.register_before_send/2` and processing should be done before this hook gets called. Using the already stored request time the formatting directive `%D - time taken to serve the request, in microseconds` should probably be what your are looking for. It might already be lying around in a local development somewhere but it will definitely be there when I have the formatters list ready.

**Comment by houshuang** [comment]
I saw you added this, thanks, it's great!

**Comment by mneudert** [comment]
You can now pass a list of formatters to the plug. I hope the docs are clear enough so you can adapt that to your usecase.

If everything looks good with that and #5 does not come back I will probably release the current master to Hex on the weekend.
